openapi: 3.0.0
info:
  title: Loan Service API
  version: 1.0.0
paths:
  /loans:
    post:
      summary: Create a new loan
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [borrowerId, principalAmount, rate, ROI]
              properties:
                borrowerId:
                  type: string
                principalAmount:
                  type: number
                rate:
                  type: number
                ROI:
                  type: number
      responses:
        '201':
          description: Loan created

  /loans/{loanId}/approve:
    post:
      summary: Approve a loan
      parameters:
        - name: loanId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [proofImageUrl, fieldValidatorId, approvalDate]
              properties:
                proofImageUrl:
                  type: string
                fieldValidatorId:
                  type: string
                approvalDate:
                  type: string
                  format: date
      responses:
        '200':
          description: Loan approved

  /loans/{loanId}/invest:
    post:
      summary: Invest in a loan
      parameters:
        - name: loanId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [investorId, amount]
              properties:
                investorId:
                  type: string
                amount:
                  type: number
      responses:
        '200':
          description: Investment successful

  /loans/{loanId}/disburse:
    post:
      summary: Disburse a loan
      parameters:
        - name: loanId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [agreementLetterUrl, fieldOfficerId, disbursementDate]
              properties:
                agreementLetterUrl:
                  type: string
                fieldOfficerId:
                  type: string
                disbursementDate:
                  type: string
                  format: date
      responses:
        '200':
          description: Loan disbursed

